sudo: false
language: groovy
jdk:
- openjdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="James Kleeh"
  - GIT_EMAIL="james.kleeh@gmail.com"
  - secure: PIY43I1IbsXRWVlD+rMILr0iGk/gbipziHb2l1fF7t+e/DeD9l3/oxMHEBtZZINRJGMPTg+fWRsr5Y9r+I5mf6FwVX8Ib9pxXHRn4cZ+rBGTUeCDVsd4L82IjsNE+JAyekvVXpl2dJHUIclqqUJK7htRtjIN15Aq71VJoulxmi0=
  - secure: vNlcrNYpWRNly+ODbku+DYDPw4YWbly9HMQos8uJTKcA3RdgiPito89qqaWZYx34DvcXUixUJrRUsfeIvKwFQoAq7uOH02MMc0JRf3edua9EDDJeVc3NwZp4MfgQyEKVcfYqeQAIMzlc+l68ailgkSjiwnZxNWLTnnYTXhVdXf4=
  - secure: Hy+yaAaxukW8ATSQaKNJpYAQ/xsAURfZu+YvdoAb7gsjk5pMSwm60WuqfH/X6UPFRI4cB1rl1kuRK4cDAEbVHlayMRK/TQX7kwl2Ehwk6vYriQBPZ+5HL528ai/hztM0kdwLjr7q5B16ptiqGWfM0bEEcjyephc90+/PcgrwcWc=
  - secure: NT2quHd+Gr4eJoyysFxrYv997DIjv6tZAUsRHrPizUIP37gWVAtmglLRkVWGZdHb3PwxiEcaK9xdF6mDJ86kYDXv2iiuft0TIB6CP7XLx/Uo69XvkDvPh0gGXzX3Co55b++OFG2MJ2HcS4Dx5cFUq0Oab1S57bg5Xh0bGJIkaa8=
  - secure: nziSDOUPYkM9/eTjJGsW6xxgsSlpX6C2NzCbO6Vsrqdc/lWfnd9OBYN66ZceA3ASXXQZmzLWn7Kut/BAf6228j9v1sFkjvkjyoZTzsbqol9wMNMTnA9it2Aj+tTZVUd7WqWwVWdCMgeYfvOa4KUV1HuQcf5wr9XTS5wmmwrNg24=
